In [1]:
import numpy as np
days=np.arange(1,11)
steps=[4555,5665,8778,9887,8997,5444,1324,4242,6556,4532]
arr=np.array([days,steps])
arr=arr.T
arr

array([[   1, 4555],
       [   2, 5665],
       [   3, 8778],
       [   4, 9887],
       [   5, 8997],
       [   6, 5444],
       [   7, 1324],
       [   8, 4242],
       [   9, 6556],
       [  10, 4532]])

In [2]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1,  6555],
       [    2,  7665],
       [    3, 10778],
       [    4, 11887],
       [    5, 10997],
       [    6,  7444],
       [    7,  3324],
       [    8,  6242],
       [    9,  8556],
       [   10,  6532]])

In [3]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    3, 10778],
       [    4, 11887],
       [    5, 10997]])